services:
  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
        - "5173:5173"
    volumes:
        - ./frontend:/app
        - /app/node_modules
    environment:
        NODE_ENV: development
    stdin_open: true
    tty: true
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - llama-pg-net
  postgres:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    ports: 
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/home/postgres/pgdata/data
    restart: always
    networks:
      - llama-pg-net
  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: ${DB_URL}
      OPENAI_API_KEY: ${VLLM_API_KEY}
    depends_on:
      - postgres
    networks:
      - llama-pg-net
  parser-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: arq src.worker.WorkerSettings
    container_name: parser-worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - llama-pg-net
  llama-pg-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.server:app --host 0.0.0.0 --port ${API_PORT:-8000} --reload
    container_name: llama-pg-api
    ports:
      - ${API_PORT:-8000}:${API_PORT:-8000}
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src/:/opt/src # for development. remove this bind mount for production
    networks:
      - llama-pg-net
    healthcheck:
      test: ["CMD", "/healthcheck.sh", "${API_PORT:-8000}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
volumes:
  pg_data:
  redis_data:
networks:
  llama-pg-net:
    driver: bridge