apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "worker.name" . }}
    helm.sh/chart: {{ include "worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.secretEnv }}
{{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
