apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama-pg.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "llama-pg.name" . }}
    helm.sh/chart: {{ include "llama-pg.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.configMapEnv }}
{{- range $key, $val := .Values.configMapEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
